# Generated by Django 5.0.1 on 2024-01-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='state',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='zip_code',
        ),
    ]
