# Generated by Django 5.0.1 on 2024-01-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_appointments_city_remove_appointments_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='address',
        ),
    ]
